FROM node:23-alpine AS server

RUN npm i -g pnpm
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

WORKDIR /app

ENV GRAPHQL_SCHEMA_PATH=./graphql-schemas/*.graphql

COPY apps/server/package.json ./

RUN pnpm install

COPY packages/graphql-schemas/ ./graphql-schemas
COPY apps/server/ .

RUN pnpm run generate && pnpm run build

EXPOSE 3000

CMD ["pnpm", "run", "start"]