import type { CodegenConfig } from '@graphql-codegen/cli';

const config: CodegenConfig = {
  overwrite: true,
  schema: process.env.GRAPHQL_SCHEMA_PATH || '../../packages/graphql-schemas/*.graphql',
  documents: 'src/graphql/*.graphql',
  generates: {
    'src/services/types.generated.ts': {
      config: {
        enumsAsTypes: true,
        useTypeImports: true,
      },
      plugins: [
        {
          add: {
            content: `/* eslint-disable */
/**
 *
 * THIS FILE IS AUTOGENERATED, DO NOT EDIT IT!
 *
 * instead, edit one of the \`.graphql\` files in this project and run
 *
 * npm run graphql-codegen
 *
 * for this file to be re-created
 */
`,
          },
        },
        'typescript',
      ],
    },
    'src/': {
      preset: 'near-operation-file',
      presetConfig: {
        baseTypesPath: 'services/types.generated.ts'
      },
      config: {
        importBaseApiFrom: '../services/graphql-api',
        exportHooks: true
      },
      plugins: [
        {
          add: {
            content: `/* eslint-disable */
/**
 *
 * THIS FILE IS AUTOGENERATED, DO NOT EDIT IT!
 *
 * instead, edit one of the \`.graphql\` files in this project and run
 *
 * npm run graphql-codegen
 *
 * for this file to be re-created
 */
`,
          },
        },
        'typescript-rtk-query',
        'typescript-operations'
      ]
    }
  },
};

export default config;
